/* Auto-generated by tools/gen_apps.py. */
#include <iros/apps.h>

static const char app_text_0[] =
    "Hello from IROS apps!\\n"
    "Use: app list | app run <name> | app info <name>\\n";

static const char app_text_1[] =
    "---\\n"
    "\\n"
    "# **Tactages Toolkit**\\n"
    "\\n"
    "**Tactages Toolkit** is a comprehensive suite of cybersecurity tools designed for network scanning, exploitation, traffic capture, brute-force attacks, packet filtering, communication testing, password cracking, SQL injection testing, web server scanning, and web application security auditing.\\n"
    "\\n"
    "---\\n"
    "\\n"
    "## **Features**\\n"
    "\\n"
    "* **Nmap** â€“ Network Scanning\\n"
    "* **Metasploit Framework** â€“ Exploitation\\n"
    "* **Wireshark** â€“ Traffic Capture\\n"
    "* **Hydra** â€“ Brute Force Attacks\\n"
    "* **Tshark** â€“ Packet Capture and Filtering\\n"
    "* **Net-tools** â€“ Network Utilities\\n"
    "* **Netcat** â€“ Network Communication\\n"
    "* **John the Ripper** â€“ Password Cracking\\n"
    "* **SQLMap** â€“ SQL Injection Testing\\n"
    "* **Nikto** â€“ Web Server Scanning\\n"
    "* **Burp Suite** â€“ Web Application Security Testing\\n"
    "\\n"
    "---\\n"
    "\\n"
    "## **Installation**\\n"
    "\\n"
    "### 1. Install Python Dependencies\\n"
    "\\n"
    "Run the following command to install required Python packages:\\n";

const iros_app_t iros_apps[] = {
    {"hello", "Built-in example app", "text", "", app_text_0},
    {"tactages", "Git app: https://github.com/IRNCyber/tactages.git", "text", "", app_text_1},
};

const u32 iros_apps_count = (u32)(sizeof(iros_apps) / sizeof(iros_apps[0]));
