import argparse
import os
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
APPS_DIR = ROOT / "apps"
APPS_INSTALLED_DIR = ROOT / "apps-installed"
OUT_C = ROOT / "kernel" / "apps_gen.c"


def c_escape(s: str) -> str:
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\r", "")
    s = s.replace("\n", "\\n")
    return s


def parse_app_file(path: Path) -> dict:
    name = None
    desc = ""
    app_type = "text"
    entry = ""
    text_lines = []
    in_text = False

    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.rstrip("\n")
        if not in_text:
            if line.strip() == "---":
                in_text = True
                continue
            m = re.match(r"^\s*name\s*=\s*(.+)\s*$", line)
            if m:
                name = m.group(1).strip()
                continue
            m = re.match(r"^\s*desc\s*=\s*(.*)\s*$", line)
            if m:
                desc = m.group(1).strip()
                continue
            m = re.match(r"^\s*type\s*=\s*(.*)\s*$", line)
            if m:
                app_type = (m.group(1).strip() or "text").lower()
                continue
            m = re.match(r"^\s*entry\s*=\s*(.*)\s*$", line)
            if m:
                entry = m.group(1).strip()
                continue
        else:
            text_lines.append(line)

    if not name:
        name = path.stem

    text = "\n".join(text_lines).strip("\n")
    return {"name": name, "desc": desc, "type": app_type, "entry": entry, "text": text}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate kernel/apps_gen.c from app manifests.")
    parser.add_argument("--include-installed", action="store_true", help="Include apps-installed/*.app too")
    args = parser.parse_args()

    apps = []

    if APPS_DIR.exists():
        for p in sorted(APPS_DIR.glob("*.app")):
            apps.append(parse_app_file(p))

    if args.include_installed and APPS_INSTALLED_DIR.exists():
        for p in sorted(APPS_INSTALLED_DIR.glob("*.app")):
            apps.append(parse_app_file(p))

    # Always include built-in "hello" app if directory is empty.
    if not apps:
        apps = [
            {
                "name": "hello",
                "desc": "Built-in example app",
                "type": "text",
                "entry": "",
                "text": "Hello from IROS apps!\nUse: app list | app run <name> | app info <name>\n",
            }
        ]

    out = []
    out.append("/* Auto-generated by tools/gen_apps.py. */")
    out.append('#include <iros/apps.h>')
    out.append("")

    for i, app in enumerate(apps):
        txt = app["text"] or ""
        out.append(f"static const char app_text_{i}[] =")
        if txt:
            for line in (txt.split("\n")):
                out.append(f'    "{c_escape(line)}\\\\n"')
            out[-1] = out[-1] + ";"  # terminate last string
        else:
            out.append('    "";')
        out.append("")

    out.append("const iros_app_t iros_apps[] = {")
    for i, app in enumerate(apps):
        out.append(
            f'    {{"{c_escape(app["name"])}", "{c_escape(app["desc"])}", "{c_escape(app["type"])}", "{c_escape(app["entry"])}", app_text_{i}}},'
        )
    out.append("};")
    out.append("")
    out.append(
        "const u32 iros_apps_count = (u32)(sizeof(iros_apps) / sizeof(iros_apps[0]));"
    )
    out.append("")

    OUT_C.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT_C}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
